### ISSUE TITLE
Error in README.markdown

### ISSUE THREAD

**Issue by calendee** [jeffturcotte/moor#12]
In Callback Parameters, I think there is a slight mistake in a sample.

Moor::route('/@class/:id/@method', '@class(uc)::@method(lc)');
// incoming /user/4/delete_me resolves to User::delete AND $_GET['id'] = 4
// incoming /user/4/run_script resolves to User::runScript AND $_GET['id'] = 4

Shouldn't that be :
// incoming /user/4/delete_me resolves to User::delete_meAND $_GET['id'] = 4  &
// incoming /user/4/run_script resolves to User::run_script AND $_GET['id'] = 4

**Comment by dotink** [comment]
I believe the (lc) after the @method converts it to lower camel case, so run_script converted to lower camel case is runScript

**Comment by calendee** [comment]
My main question is with delete_me supposedly resolving to User::delete.   It should be at least User::deleteMe

**Comment by jeffturcotte** [comment]
This was an error in the docs. fixed.
