### ISSUE TITLE
preg match error Moor.php on line 1066 (missing parenthesis)

### ISSUE THREAD

**Issue by lekoala** [jeffturcotte/moor#16]
this

preg_match('/(?P<namespace>._)\\(?P<short_class>)[a-zA-Z][a-zA-Z0-9]_)$/', $class, $matches);

should be

preg_match('/(?P<namespace>._)\\(?P<short_class>[a-zA-Z][a-zA-Z0-9]_)$/', $class, $matches); 

or maybe I missed something, but just in case you know now

**Comment by mattsah** [comment]
This is fixed in the dotink fork if you want to try that

**Comment by jeffturcotte** [comment]
Fixed in eead63e
