### ISSUE TITLE
Seriously man, no dash?

### ISSUE THREAD

**Issue by dotink** [jeffturcotte/moor#4]
Ok, I understand it might be very common to use dashes to separate possible GET/PUT parameters such as 2009-07-19 to get :year, :month, :day -- but really you need to add the - to the default regex, because it's just as easy for them to get the full date an parse it in PHP as it is for you to parse it.

**Comment by wbond** [comment]
Just call: Moor::setRequestParamPattern('[A-Za-z0-9_-]+');

**Comment by mattsah** [comment]
While I still think the dash should be in there by default, I'm closing this as it will likely never be changed upstream and can still be overridden as @wbond hs suggested.
