### ISSUE TITLE
Route Specificity

### ISSUE THREAD

**Issue by dotink** [jeffturcotte/moor#6]
Would it be possible and or meaningful to add route specificity?  I'm thinking of something like CSS specificity where certain tokens in routes add to specificity and when the route is actually dispatched the chosen route would be the route with the highest specificity matching the request URI.

Right now it seems as if first matched route takes the cake, it would be nicer if BEST matched route took the cake.  Or perhaps I'm missing something.

**Comment by jeffturcotte** [comment]
This will never happen! :) Closing.
