### ISSUE TITLE
Require statements break when using __autoload

### ISSUE THREAD

**Issue by wbond** [jeffturcotte/moor#7]
I have a class that extends MoorAbstractController, and a method on that gets called before any methods are called on the Moor class. The autoloader loads the MoorAbstractController class, but then the Moor class does a straight-up require for MoorAbstractController, causing a fatal error.

Either the require statements should be removed, or they should be switched to require_once.

**Comment by wbond** [comment]
I suppose you could also check to see if the abstract controller class is loaded before calling require.

**Comment by mattsah** [comment]
I believe this is fixed in all recent versions by using class exists without autoloading.  Closing.
